Mamman222021b: myset.o Error_Examiner.o set.o
	gcc -g -Wall -ansi -pedantic myset.o Error_Examiner.o set.o -o Mamman222021b 
set.o: set.c set.h
	gcc -c -Wall -ansi -pedantic set.c -o set.o
Error_Examiner.o: Error_Examiner.c
	gcc -c -Wall -ansi -pedantic Error_Examiner.c -o Error_Examiner.o
myset.o: myset.c set.h
	gcc -c -Wall -ansi -pedantic myset.c -o myset.o 
